export const demoDestinations = [
  {
    id: "bali-indonesia",
    name: "Bali",
    country: "Indonesia",
    region: "Lesser Sunda Islands",
    destination_type: "beach",
    budget_tier: "mid_range",
    best_travel_months: ["04", "05", "06", "09"],
    tagline: "Rice terraces, surf breaks, temple mornings, and slow coastal stays.",
    overview:
      "Bali works well for travelers who want a mix of beach time, cultural stops, day trips, and easy food options. Start with Ubud for temples and rice fields, then move south for surf, sunsets, and island-hopping.",
    cover_image:
      "https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=80",
    duration: "6-9 days",
    rating: "4.8",
    starting_price: "$820",
    highlights: ["Ubud", "Uluwatu", "Nusa Penida"],
  },
  {
    id: "kyoto-japan",
    name: "Kyoto",
    country: "Japan",
    region: "Kansai",
    destination_type: "cultural",
    budget_tier: "premium",
    best_travel_months: ["03", "04", "10", "11"],
    tagline: "Historic lanes, shrine walks, tea houses, and seasonal gardens.",
    overview:
      "Kyoto is best for slow exploration across temple districts, traditional neighborhoods, markets, and nearby mountain routes. It pairs naturally with Osaka or Nara for a broader Kansai trip.",
    cover_image:
      "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=80",
    duration: "4-6 days",
    rating: "4.9",
    starting_price: "$1,140",
    highlights: ["Fushimi Inari", "Gion", "Arashiyama"],
  },
  {
    id: "santorini-greece",
    name: "Santorini",
    country: "Greece",
    region: "Cyclades",
    destination_type: "island",
    budget_tier: "premium",
    best_travel_months: ["05", "06", "09", "10"],
    tagline: "Clifftop villages, volcanic beaches, boat days, and Aegean sunsets.",
    overview:
      "Santorini is compact but high-impact, with scenic village walks, caldera views, wineries, beaches, and short boat excursions. It suits couples, small groups, and relaxed island itineraries.",
    cover_image:
      "https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1200&q=80",
    duration: "3-5 days",
    rating: "4.7",
    starting_price: "$1,260",
    highlights: ["Oia", "Fira", "Caldera cruise"],
  },
  {
    id: "banff-canada",
    name: "Banff",
    country: "Canada",
    region: "Alberta",
    destination_type: "mountain",
    budget_tier: "mid_range",
    best_travel_months: ["06", "07", "08", "09"],
    tagline: "Glacial lakes, alpine drives, day hikes, and mountain lodges.",
    overview:
      "Banff is built for scenic road trips and outdoor days. Lake Louise, Moraine Lake, gondola viewpoints, and accessible hikes make it easy to shape a trip around comfort or adventure.",
    cover_image:
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
    duration: "5-7 days",
    rating: "4.8",
    starting_price: "$980",
    highlights: ["Lake Louise", "Moraine Lake", "Icefields Parkway"],
  },
  {
    id: "marrakesh-morocco",
    name: "Marrakesh",
    country: "Morocco",
    region: "Marrakesh-Safi",
    destination_type: "city",
    budget_tier: "value",
    best_travel_months: ["03", "04", "10", "11"],
    tagline: "Medina stays, garden afternoons, market food, and desert add-ons.",
    overview:
      "Marrakesh is a strong base for travelers who want color, food, architecture, and day trips. Build the plan around the medina, historic palaces, Majorelle Garden, and Atlas Mountain routes.",
    cover_image:
      "https://images.unsplash.com/photo-1597212720412-8f1ef4d46dc5?auto=format&fit=crop&w=1200&q=80",
    duration: "4-7 days",
    rating: "4.6",
    starting_price: "$640",
    highlights: ["Medina", "Majorelle Garden", "Atlas Mountains"],
  },
  {
    id: "queenstown-new-zealand",
    name: "Queenstown",
    country: "New Zealand",
    region: "Otago",
    destination_type: "adventure",
    budget_tier: "premium",
    best_travel_months: ["01", "02", "03", "12"],
    tagline: "Lake views, thrill activities, wine country, and South Island drives.",
    overview:
      "Queenstown is ideal for active trips with a polished base. Mix lake cruises, mountain viewpoints, adventure sports, wineries, and day trips toward Glenorchy or Milford Sound.",
    cover_image:
      "https://images.unsplash.com/photo-1507699622108-4be3abd695ad?auto=format&fit=crop&w=1200&q=80",
    duration: "5-8 days",
    rating: "4.9",
    starting_price: "$1,380",
    highlights: ["Lake Wakatipu", "Glenorchy", "Milford Sound"],
  },
];
